import "./globals.css";
import { Montserrat } from 'next/font/google'

export const metadata = {
  title: "SpicyBets",
  description: "Generated by create next app",
};

const inter = Montserrat({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
